# Generated by Django 4.2.1 on 2023-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
