# Generated by Django 4.2.1 on 2023-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
